<?php
/**
 * @var $block \SuttonSilver\Testimonials\Block\TestimonialList
 */
?>
<div class="container">
	<?php $collection = $block->getLoadedCollection(); ?>
	<?php foreach($collection as $item): ?>
        <div class="flex-container">
            <div class="testimonial vertical-center center">
                <?= $item->getTestimonial(); ?>
                <div class="author">
                    <span class="name"><?= $item->getName(); ?></span>
                    <span class="email"><?= $item->getEmail(); ?></span>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>